# Generated by Django 3.2.5 on 2021-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210723_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
