# Generated by Django 3.2.5 on 2021-12-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.FloatField(default=1934.23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price_for_3_nights',
            field=models.FloatField(default=3344),
            preserve_default=False,
        ),
    ]
