# Generated by Django 3.2.5 on 2021-12-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211204_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
