# Generated by Django 3.2.5 on 2021-12-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211205_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='Имя',
        ),
        migrations.RemoveField(
            model_name='room',
            name='booked',
        ),
    ]
