# Generated by Django 3.2.5 on 2021-07-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_developers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=512)),
                ('photo', models.ImageField(upload_to='8901.jpg')),
            ],
        ),
        migrations.DeleteModel(
            name='Developers',
        ),
    ]
