# Generated by Django 3.2.5 on 2021-12-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211206_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Имя',
            new_name='name',
        ),
    ]
