# Generated by Django 3.2.5 on 2021-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210724_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='photo',
            field=models.ImageField(default='img/8901.jpg', upload_to='img'),
        ),
    ]
