# Generated by Django 3.2.5 on 2021-12-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_имя_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
    ]
