# Generated by Django 3.2.5 on 2021-12-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_room_room_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='BookedRoom',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='count',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
