# Generated by Django 3.2.5 on 2021-12-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211206_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='gallery')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='ImageRoom',
        ),
    ]
