# Generated by Django 3.2.5 on 2021-12-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211208_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedroom',
            options={'ordering': ('-start_date', 'last_name'), 'verbose_name_plural': 'Забронированные номера'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='imageroom',
            options={'verbose_name_plural': 'Фото комнат'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': 'Типы комнат'},
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='price_for_3_nights',
        ),
        migrations.AlterField(
            model_name='bookedroom',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='bookedroom',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='bookedroom',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bookedroom',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='bookedroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roomtype', verbose_name='Тип комнаты'),
        ),
        migrations.AlterField(
            model_name='bookedroom',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery', verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='imageroom',
            name='image',
            field=models.ImageField(null=True, upload_to='img', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='imageroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roomtype', verbose_name='Тип комнаты'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(max_length=100, verbose_name='Тип комнаты'),
        ),
    ]
